# fly.toml app configuration file generated for foodshare-api on 2024-04-24T01:11:24+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foodshare-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
